"""
pipeline/seed_commercial_projects.py
-------------------------------------
Seeds 67 landmark commercial, private industrial, banking, data center,
healthcare, and mixed-use developments across Indonesia.
"""
import sqlite3
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from pipeline.storage.geojson_export import export_geojson

DB_PATH = Path("data/projects.sqlite")
GEOJSON_PATH = Path("data/projects.geojson")

COMMERCIAL_PROJECTS = [
    # ── 1. Banking & Corporate Headquarters ──────────────────────────────────────
    {
        "project_id": "swasta-batam-001",
        "project_name": "Pembangunan Gedung Perbankan Batam",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 0.185,
        "budget_raw": "Rp 185 Miliar",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Mandiri (Persero) Tbk / Sektor Perbankan",
        "unor": "Gedung Komersial Swasta",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 42.5,
        "province": "Kepulauan Riau",
        "regency": "Kota Batam",
        "latitude": 1.1301,
        "longitude": 104.0305,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jkt-001",
        "project_name": "Menara Danareksa Jakarta",
        "category": "Commercial & Private",
        "status": "Completed",
        "budget_idr": 0.814,
        "budget_raw": "Rp 814 Miliar",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Danareksa (Persero) & PT PP (Persero) Tbk",
        "unor": "Commercial Grade-A Office Tower",
        "balai": None,
        "fiscal_year": "2023",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.1818,
        "longitude": 106.8272,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jkt-002",
        "project_name": "BSI Tower Jakarta (Gedung Landmark Bank Syariah Indonesia)",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.100,
        "budget_raw": "Rp 1,10 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Syariah Indonesia Tbk",
        "unor": "Headquarters Bank Tower",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 35.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.1825,
        "longitude": 106.8255,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jkt-003",
        "project_name": "Menara BCA Grand Indonesia",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.500,
        "budget_raw": "Rp 1,50 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Central Asia Tbk / Djarum Group",
        "unor": "Headquarters Grade-A Tower",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.1950,
        "longitude": 106.8219,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-004",
        "project_name": "Menara Astra Jakarta",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.200,
        "budget_raw": "Rp 2,20 Triliun",
        "contractor": "Shimizu - PT Total Bangun Persada KSO",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Astra International Tbk",
        "unor": "Corporate Headquarters Landmark",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.2081,
        "longitude": 106.8215,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-005",
        "project_name": "Autograph Tower Thamrin Nine (Supertall)",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 4.500,
        "budget_raw": "Rp 4,50 Triliun",
        "contractor": "PT Acset Indonusa - Samsung C&T KSO",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Putragaya Wahana",
        "unor": "Supertall Tower (382.9 m)",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.2001,
        "longitude": 106.8228,
        "source_url": "https://acset.co",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-006",
        "project_name": "Luminary Tower Thamrin Nine",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 2.800,
        "budget_raw": "Rp 2,80 Triliun",
        "contractor": "PT Acset Indonusa Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Putragaya Wahana",
        "unor": "Supertall Mixed-Use Tower (304 m)",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 82.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.2008,
        "longitude": 106.8222,
        "source_url": "https://acset.co",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-007",
        "project_name": "Menara BRI Gatot Subroto",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.150,
        "budget_raw": "Rp 1,15 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Rakyat Indonesia (Persero) Tbk",
        "unor": "Corporate Banking Tower",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2341,
        "longitude": 106.8265,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jkt-008",
        "project_name": "Treasury Tower District 8 SCBD",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.700,
        "budget_raw": "Rp 2,70 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Agung Sedayu Group",
        "unor": "SCBD Financial Landmark (280 m)",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2268,
        "longitude": 106.8091,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-009",
        "project_name": "Menara BTPN Mega Kuningan",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.300,
        "budget_raw": "Rp 1,30 Triliun",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank BTPN Tbk / Sumitomo Mitsui",
        "unor": "Grade-A Banking Tower",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2285,
        "longitude": 106.8260,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-010",
        "project_name": "Menara Mandiri Sudirman Tower 1 & 2",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.400,
        "budget_raw": "Rp 1,40 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Mandiri (Persero) Tbk",
        "unor": "Headquarters Plaza Mandiri",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2248,
        "longitude": 106.8062,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jkt-011",
        "project_name": "Sinarmas MSIG Tower Sudirman",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.850,
        "budget_raw": "Rp 1,85 Triliun",
        "contractor": "PT Acset Indonusa Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Sinarmas Land & MSIG Insurance",
        "unor": "Grade-A Office Tower (245 m)",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2135,
        "longitude": 106.8219,
        "source_url": "https://acset.co",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-012",
        "project_name": "Sequis Tower SCBD",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.100,
        "budget_raw": "Rp 2,10 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Gunung Sewu Kencana / FARPOINT",
        "unor": "LEED Platinum Commercial Tower",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2260,
        "longitude": 106.8085,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-bdg-001",
        "project_name": "Gedung Kantor Pusat Bank BJB Bandung",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.750,
        "budget_raw": "Rp 750 Miliar",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank BJB Tbk",
        "unor": "Regional Banking Headquarters",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kota Bandung",
        "latitude": -6.9174,
        "longitude": 107.6094,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-sby-001",
        "project_name": "Menara Bank Mega Regional Surabaya",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.550,
        "budget_raw": "Rp 550 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "CT Corp / PT Bank Mega Tbk",
        "unor": "Commercial Office Tower",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kota Surabaya",
        "latitude": -7.2642,
        "longitude": 112.7483,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-sby-002",
        "project_name": "Grha CIMB Niaga Surabaya",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.480,
        "budget_raw": "Rp 480 Miliar",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank CIMB Niaga Tbk",
        "unor": "Commercial Banking Center",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kota Surabaya",
        "latitude": -7.2690,
        "longitude": 112.7431,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-mdn-001",
        "project_name": "Menara BRI Medan Podomoro City",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.650,
        "budget_raw": "Rp 650 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Agung Podomoro Land & Bank BRI",
        "unor": "Grade-A Regional Office Tower",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Sumatera Utara",
        "regency": "Kota Medan",
        "latitude": 3.5935,
        "longitude": 98.6738,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },

    # ── 2. Hyperscale Data Centers & Tech Parks ─────────────────────────────────
    {
        "project_id": "swasta-batam-002",
        "project_name": "Hyperscale Data Center Nongsa Digital Park Batam",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.250,
        "budget_raw": "Rp 1,25 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Nongsa Digital Park / Konsorsium Data Center Swasta",
        "unor": "Data Center & Tech Hub",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 68.0,
        "province": "Kepulauan Riau",
        "regency": "Kota Batam",
        "latitude": 1.1834,
        "longitude": 104.1082,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-batam-003",
        "project_name": "Mandiri IT Center & Disaster Recovery Batam",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 0.320,
        "budget_raw": "Rp 320 Miliar",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Mandiri (Persero) Tbk",
        "unor": "IT Infrastructure & Security Hub",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 55.0,
        "province": "Kepulauan Riau",
        "regency": "Kota Batam",
        "latitude": 1.1215,
        "longitude": 104.0512,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-001",
        "project_name": "DCI Indonesia Hyperscale Campus H2 Karawang",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 3.200,
        "budget_raw": "Rp 3,20 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT DCI Indonesia Tbk & Salim Group",
        "unor": "Hyperscale Tier-IV Data Campus",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 70.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Karawang",
        "latitude": -6.3712,
        "longitude": 107.2910,
        "source_url": "https://dci-indonesia.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-002",
        "project_name": "DCI Indonesia Campus Cibitung JK1-JK5",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 4.500,
        "budget_raw": "Rp 4,50 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT DCI Indonesia Tbk / Equinix Partner",
        "unor": "Tier-IV Hyperscale Data Center",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.2750,
        "longitude": 107.1065,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-003",
        "project_name": "Telkom Hyperscale Data Center Cikarang HDC 1",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.800,
        "budget_raw": "Rp 1,80 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Telkom Data Ekosistem (NeutraDC)",
        "unor": "Carrier-Neutral Hyperscale Facility",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.3421,
        "longitude": 107.1652,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-004",
        "project_name": "Telkom Hyperscale Data Center Cikarang HDC 2",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.950,
        "budget_raw": "Rp 1,95 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Telkom Data Ekosistem (NeutraDC)",
        "unor": "Hyperscale Expansion Module",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 45.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.3425,
        "longitude": 107.1660,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-005",
        "project_name": "PDG Hyperscale Data Center Cibitung JC2",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 2.500,
        "budget_raw": "Rp 2,50 Triliun",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Princeton Digital Group (PDG)",
        "unor": "120 MW Hyperscale Campus",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 62.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.2820,
        "longitude": 107.0945,
        "source_url": "https://princetondg.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-006",
        "project_name": "STT GDC Indonesia Hyperscale Campus Cikarang",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 2.100,
        "budget_raw": "Rp 2,10 Triliun",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "ST Telemedia Global Data Centres",
        "unor": "72 MW Data Center Facility",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 78.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.3250,
        "longitude": 107.1420,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-007",
        "project_name": "NTT Global Data Center JKT3 Cikarang",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.750,
        "budget_raw": "Rp 1,75 Triliun",
        "contractor": "PT Kajima Indonesia - PT Wijaya Karya KSO",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "NTT Ltd / NTT Communications",
        "unor": "Hyperscale Data Center JKT3",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.3310,
        "longitude": 107.1580,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-008",
        "project_name": "EdgeConneX Hyperscale Data Center Bekasi JTX01",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 2.400,
        "budget_raw": "Rp 2,40 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "EdgeConneX / EQT Infrastructure",
        "unor": "90 MW Hyperscale Center",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 65.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.2910,
        "longitude": 107.0850,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-batam-004",
        "project_name": "GDS Hyperscale Data Center Campus Nongsa",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 3.100,
        "budget_raw": "Rp 3,10 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "GDS Holdings Ltd / ST Telemedia",
        "unor": "54 MW Cross-Border Cloud Hub",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 52.0,
        "province": "Kepulauan Riau",
        "regency": "Kota Batam",
        "latitude": 1.1850,
        "longitude": 104.1120,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-009",
        "project_name": "BDx Indonesia Hyperscale CGK4 Jatiluhur",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.600,
        "budget_raw": "Rp 1,60 Triliun",
        "contractor": "PT Adhi Karya (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Big Data Exchange (BDx) / Indosat",
        "unor": "100 MW Renewable Powered Center",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 40.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Purwakarta",
        "latitude": -6.5310,
        "longitude": 107.4120,
        "source_url": "https://adhi.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },

    # ── 3. Private Hospitals & Healthcare Hubs ──────────────────────────────────
    {
        "project_id": "swasta-ikn-001",
        "project_name": "Mayapada Hospital Nusantara IKN",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 0.500,
        "budget_raw": "Rp 500 Miliar",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Mayapada Healthcare Group (PT Sejahteraraya Anugrahjaya Tbk)",
        "unor": "Green Hospital IKN Nusantara",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 85.0,
        "province": "Kalimantan Timur",
        "regency": "Kabupaten Penajam Paser Utara",
        "latitude": -0.9632,
        "longitude": 116.7112,
        "source_url": "https://mayapadahospital.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-btn-001",
        "project_name": "RS Siloam Hospital Lippo Village Karawaci",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.850,
        "budget_raw": "Rp 850 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Siloam International Hospitals Tbk",
        "unor": "Private Flagship General Hospital",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Banten",
        "regency": "Kabupaten Tangerang",
        "latitude": -6.2235,
        "longitude": 106.6085,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-bdg-002",
        "project_name": "Mayapada Hospital Bandung",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.650,
        "budget_raw": "Rp 650 Miliar",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Mayapada Healthcare Group",
        "unor": "Tertiary General Hospital",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kota Bandung",
        "latitude": -6.9420,
        "longitude": 107.6250,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-013",
        "project_name": "RS Mitra Keluarga Slipi Jakarta",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.450,
        "budget_raw": "Rp 450 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Mitra Keluarga Karyasehat Tbk",
        "unor": "Private Specialized Hospital",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Barat",
        "latitude": -6.1870,
        "longitude": 106.7972,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-btn-002",
        "project_name": "RS Pondok Indah Bintaro Jaya",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.700,
        "budget_raw": "Rp 700 Miliar",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Binara Guna Mediktama",
        "unor": "Eco-Hospital Bintaro Jaya",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Banten",
        "regency": "Kota Tangerang Selatan",
        "latitude": -6.2845,
        "longitude": 106.7125,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-mdn-002",
        "project_name": "RS Columbia Asia Hospital Medan",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.400,
        "budget_raw": "Rp 400 Miliar",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Columbia Asia Group",
        "unor": "Tertiary Medical Center",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Sumatera Utara",
        "regency": "Kota Medan",
        "latitude": 3.5890,
        "longitude": 98.6750,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-plm-001",
        "project_name": "RS Siloam Sriwijaya Palembang",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.380,
        "budget_raw": "Rp 380 Miliar",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Siloam International Hospitals Tbk",
        "unor": "Private Specialized Hospital",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "Sumatera Selatan",
        "regency": "Kota Palembang",
        "latitude": -2.9730,
        "longitude": 104.7450,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-sby-003",
        "project_name": "Mayapada Hospital Surabaya",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.600,
        "budget_raw": "Rp 600 Miliar",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Mayapada Healthcare Group",
        "unor": "Modern General Hospital Surabaya",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kota Surabaya",
        "latitude": -7.3180,
        "longitude": 112.7290,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-bpn-001",
        "project_name": "RS Siloam Hospital Balikpapan",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.350,
        "budget_raw": "Rp 350 Miliar",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Siloam International Hospitals Tbk",
        "unor": "Specialist Private Hospital",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "Kalimantan Timur",
        "regency": "Kota Balikpapan",
        "latitude": -1.2480,
        "longitude": 116.8850,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-bli-001",
        "project_name": "Bali International Hospital Sanur (KEK Kesehatan)",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.450,
        "budget_raw": "Rp 1,45 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Pertamina Bina Medika IHC & Mayo Clinic Partner",
        "unor": "International Medical Tourism Hub",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 92.0,
        "province": "Bali",
        "regency": "Kota Denpasar",
        "latitude": -8.6770,
        "longitude": 115.2630,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },

    # ── 4. Mixed-Use, TODs & Commercial Megaprojects ────────────────────────────
    {
        "project_id": "swasta-batam-005",
        "project_name": "Pollux Meisterstadt Batam (Habibie Complex)",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 4.200,
        "budget_raw": "Rp 4,20 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Pollux Barelang Megasuperblok",
        "unor": "Integrated Megasuperblock Batam",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Kepulauan Riau",
        "regency": "Kota Batam",
        "latitude": 1.1185,
        "longitude": 104.0412,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jkt-014",
        "project_name": "LRT City Ciracas (Urban Signatures)",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.300,
        "budget_raw": "Rp 1,30 Triliun",
        "contractor": "PT Adhi Karya (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Adhi Commuter Properti Tbk",
        "unor": "Transit-Oriented Development (TOD)",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 75.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Timur",
        "latitude": -6.3260,
        "longitude": 106.8775,
        "source_url": "https://adhi.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-010",
        "project_name": "LRT City Sentul (Royal Sentul Park)",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.100,
        "budget_raw": "Rp 1,10 Triliun",
        "contractor": "PT Adhi Karya (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Adhi Commuter Properti Tbk",
        "unor": "TOD Residential & Commercial",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bogor",
        "latitude": -6.5310,
        "longitude": 106.8620,
        "source_url": "https://adhi.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-011",
        "project_name": "LRT City Bekasi Timur (Eastern Green)",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.400,
        "budget_raw": "Rp 1,40 Triliun",
        "contractor": "PT Adhi Karya (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Adhi Commuter Properti Tbk",
        "unor": "Transit-Oriented Development",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kota Bekasi",
        "latitude": -6.2580,
        "longitude": 107.0210,
        "source_url": "https://adhi.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-012",
        "project_name": "Vasanta Innopark MM2100 Cikarang",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.500,
        "budget_raw": "Rp 2,50 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Vasanta Group & Mitsubishi Corporation",
        "unor": "Japanese Township & Commercial Complex",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.3020,
        "longitude": 107.0980,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-sby-004",
        "project_name": "Ciputra World Surabaya Phase 3 & 4",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.800,
        "budget_raw": "Rp 1,80 Triliun",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Ciputra Development Tbk",
        "unor": "Mixed-Use Mall & SOHO Tower",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kota Surabaya",
        "latitude": -7.2910,
        "longitude": 112.7190,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-sby-005",
        "project_name": "Pakuwon City Mall & East Coast Center",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.500,
        "budget_raw": "Rp 1,50 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Pakuwon Jati Tbk",
        "unor": "Commercial Lifestyle Center",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kota Surabaya",
        "latitude": -7.2750,
        "longitude": 112.8050,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-sby-006",
        "project_name": "Grand Sagara Surabaya (Kenjeran Waterfront)",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.900,
        "budget_raw": "Rp 1,90 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT PP Properti Tbk",
        "unor": "Waterfront Mixed Development",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 48.0,
        "province": "Jawa Timur",
        "regency": "Kota Surabaya",
        "latitude": -7.2410,
        "longitude": 112.7980,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-mdn-003",
        "project_name": "Podomoro City Deli Medan Mixed-Use",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 3.500,
        "budget_raw": "Rp 3,50 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Agung Podomoro Land",
        "unor": "Landmark Superblock (Towers, Mall, SOHO)",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Sumatera Utara",
        "regency": "Kota Medan",
        "latitude": 3.5940,
        "longitude": 98.6740,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-015",
        "project_name": "Ciputra International Puri Jakarta",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.200,
        "budget_raw": "Rp 2,20 Triliun",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Ciputra Development Tbk",
        "unor": "Commercial Complex & Towers",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Barat",
        "latitude": -6.1820,
        "longitude": 106.7410,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-016",
        "project_name": "Senayan City Mall & Tower Complex",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 3.000,
        "budget_raw": "Rp 3,00 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Agung Podomoro Land",
        "unor": "Commercial Shopping & Offices",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.2270,
        "longitude": 106.7975,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-017",
        "project_name": "Central Park & Neo Soho Mall Jakarta",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 4.000,
        "budget_raw": "Rp 4,00 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Agung Podomoro Land",
        "unor": "Megasuperblock Commercial Center",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Barat",
        "latitude": -6.1770,
        "longitude": 106.7910,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-batam-006",
        "project_name": "One Avenue Batam Commercial Mixed-Use",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 1.100,
        "budget_raw": "Rp 1,10 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Nirvana Realty / One Avenue",
        "unor": "Commercial Hub & Residence",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 60.0,
        "province": "Kepulauan Riau",
        "regency": "Kota Batam",
        "latitude": 1.1250,
        "longitude": 104.0480,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-013",
        "project_name": "Pakuwon Mall Bekasi & Pakuwon Residences",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 2.200,
        "budget_raw": "Rp 2,20 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Pakuwon Jati Tbk",
        "unor": "Superblock Mall & Residential Towers",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 72.0,
        "province": "Jawa Barat",
        "regency": "Kota Bekasi",
        "latitude": -6.2410,
        "longitude": 106.9950,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-014",
        "project_name": "Grand Kamala Lagoon Kalimalang Bekasi",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.600,
        "budget_raw": "Rp 2,60 Triliun",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT PP Properti Tbk",
        "unor": "Mixed-Use CBD Township",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kota Bekasi",
        "latitude": -6.2520,
        "longitude": 106.9740,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },

    # ── 5. Private Clean Industrial, Smelters & Advanced Manufacturing ──────────
    {
        "project_id": "swasta-jtm-001",
        "project_name": "Smelter Tembaga PT Freeport Indonesia Manyar Gresik",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 42.000,
        "budget_raw": "Rp 42,0 Triliun (USD 3,0B)",
        "contractor": "Chiyoda - PT Wijaya Karya (WIKA) KSO",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Freeport Indonesia",
        "unor": "Single-Line Copper Smelter",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kabupaten Gresik",
        "latitude": -7.1120,
        "longitude": 112.6050,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-ntb-001",
        "project_name": "Smelter Tembaga & Emas PT Amman Mineral Industri Sumbawa",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 14.500,
        "budget_raw": "Rp 14,5 Triliun (USD 980M)",
        "contractor": "PT PP - China Nonferrous KSO",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Amman Mineral Industri Tbk",
        "unor": "Copper & Gold Smelter Facility",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 95.0,
        "province": "Nusa Tenggara Barat",
        "regency": "Kabupaten Sumbawa Barat",
        "latitude": -8.7610,
        "longitude": 116.7820,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-015",
        "project_name": "Pabrik Sel Baterai EV PT HLI Green Power Karawang",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 15.600,
        "budget_raw": "Rp 15,6 Triliun (USD 1,1B)",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT HLI Green Power (Hyundai Motor & LG Energy Solution)",
        "unor": "10 GWh EV Battery Cell Gigafactory",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Karawang",
        "latitude": -6.3680,
        "longitude": 107.2710,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-016",
        "project_name": "Pabrik Mobil PT Hyundai Motor Manufacturing Cikarang",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 21.000,
        "budget_raw": "Rp 21,0 Triliun (USD 1,5B)",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Hyundai Motor Company",
        "unor": "Manufacturing & EV Assembly Plant",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.3650,
        "longitude": 107.1850,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-017",
        "project_name": "Pabrik Mobil PT SGMW Wuling Motor Indonesia Cikarang",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 10.000,
        "budget_raw": "Rp 10,0 Triliun (USD 700M)",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "SAIC-GM-Wuling Automobile",
        "unor": "Automobile & EV Production Hub",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Bekasi",
        "latitude": -6.3520,
        "longitude": 107.1680,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-btn-003",
        "project_name": "Kompleks Petrokimia PT Lotte Chemical Titan Cilegon (LINE Project)",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 58.000,
        "budget_raw": "Rp 58,0 Triliun (USD 3,9B)",
        "contractor": "PT PP - Lotte E&C KSO",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Lotte Chemical Indonesia",
        "unor": "Naphtha Cracker Petrochemical Complex",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 88.0,
        "province": "Banten",
        "regency": "Kota Cilegon",
        "latitude": -5.9920,
        "longitude": 106.0120,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-mlk-001",
        "project_name": "Smelter Nikel HPAL PT Trimegah Bangun Persada (Harita) Pulau Obi",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 18.000,
        "budget_raw": "Rp 18,0 Triliun",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Harita Nickel Group",
        "unor": "HPAL Battery Raw Material Smelter",
        "balai": None,
        "fiscal_year": "2023",
        "progress": 100.0,
        "province": "Maluku Utara",
        "regency": "Kabupaten Halmahera Selatan",
        "latitude": -1.5420,
        "longitude": 127.6320,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-slt-001",
        "project_name": "Kawasan Industri PT IMIP Morowali Extension",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 25.000,
        "budget_raw": "Rp 25,0 Triliun",
        "contractor": "PT PP - PT Bintang Delapan KSO",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Indonesia Morowali Industrial Park (IMIP)",
        "unor": "Stainless Steel & Battery Grade Industrial Park",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 80.0,
        "province": "Sulawesi Tengah",
        "regency": "Kabupaten Morowali",
        "latitude": -2.8310,
        "longitude": 122.1580,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-slt-002",
        "project_name": "Smelter Nikel HPAL PT Vale Indonesia Pomalaa Block",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 37.500,
        "budget_raw": "Rp 37,5 Triliun (USD 2,5B)",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Vale Indonesia Tbk & Zhejiang Huayou Cobalt",
        "unor": "HPAL Processing Facility",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 45.0,
        "province": "Sulawesi Tenggara",
        "regency": "Kabupaten Kolaka",
        "latitude": -4.1820,
        "longitude": 121.6110,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jtg-001",
        "project_name": "Pabrik Semen PT Semen Grobogan",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 4.500,
        "budget_raw": "Rp 4,50 Triliun",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Semen Grobogan",
        "unor": "Integrated Cement Manufacturing Plant",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Tengah",
        "regency": "Kabupaten Grobogan",
        "latitude": -7.0310,
        "longitude": 110.8250,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-slt-003",
        "project_name": "Fasilitas Pemurnian Feronikel Kolaka Antam",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 5.200,
        "budget_raw": "Rp 5,20 Triliun",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Aneka Tambang Tbk (Antam)",
        "unor": "FeNi Smelter Modernization",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Sulawesi Tenggara",
        "regency": "Kabupaten Kolaka",
        "latitude": -4.1520,
        "longitude": 121.5850,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jtm-002",
        "project_name": "Kawasan Industri JIIPE Commercial Terminal Port",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 6.800,
        "budget_raw": "Rp 6,80 Triliun",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT AKR Corporindo Tbk & PT Pelabuhan Indonesia",
        "unor": "Integrated Deep Sea Commercial Port",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kabupaten Gresik",
        "latitude": -7.1080,
        "longitude": 112.6120,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-batam-007",
        "project_name": "Pabrik Kaca Solar Panel Xinyi Glass Rempang Batam",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 11.500,
        "budget_raw": "Rp 11,5 Triliun (USD 800M)",
        "contractor": "PT PP (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Xinyi International Investment Ltd",
        "unor": "Photovoltaic Solar Glass Manufacturing Hub",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 30.0,
        "province": "Kepulauan Riau",
        "regency": "Kota Batam",
        "latitude": 0.8850,
        "longitude": 104.1680,
        "source_url": "https://ptpp.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jkt-018",
        "project_name": "Menara Binavest Tower Sudirman",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.950,
        "budget_raw": "Rp 950 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bina Investa Prima",
        "unor": "Commercial Grade-A Office",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2190,
        "longitude": 106.8190,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-019",
        "project_name": "Menara Kompas Gramedia Palmerah",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.820,
        "budget_raw": "Rp 820 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Kompas Gramedia Group",
        "unor": "Media & Technology Headquarters",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.2080,
        "longitude": 106.7950,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-020",
        "project_name": "Pondok Indah Mall 3 & Office Tower",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.300,
        "budget_raw": "Rp 2,30 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Metropolitan Kentjana Tbk",
        "unor": "Luxury Mall & Commercial Center",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2650,
        "longitude": 106.7840,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-021",
        "project_name": "LRT City Tebet (The Premiere MTH)",
        "category": "Commercial & Private",
        "status": "Construction",
        "budget_idr": 0.980,
        "budget_raw": "Rp 980 Miliar",
        "contractor": "PT Adhi Karya (Persero) Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Adhi Commuter Properti Tbk",
        "unor": "TOD Office & Commercial Hub",
        "balai": None,
        "fiscal_year": "2024",
        "progress": 68.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2420,
        "longitude": 106.8610,
        "source_url": "https://adhi.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-btn-004",
        "project_name": "Kawasan Industri Modern Cikande Logistics Center",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.700,
        "budget_raw": "Rp 1,70 Triliun",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Modernland Realty Tbk",
        "unor": "Heavy Industrial & Smart Logistics Estate",
        "balai": None,
        "fiscal_year": "2022",
        "progress": 100.0,
        "province": "Banten",
        "regency": "Kabupaten Serang",
        "latitude": -6.1850,
        "longitude": 106.3520,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-018",
        "project_name": "Pabrik Kaca Asahi Flat Glass Cikampek",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 3.800,
        "budget_raw": "Rp 3,80 Triliun",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Asahimas Flat Glass Tbk",
        "unor": "Industrial Flat Glass Furnace",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kabupaten Karawang",
        "latitude": -6.4150,
        "longitude": 107.4520,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-jbr-019",
        "project_name": "Summarecon Mall Bandung & Gedung Komersial",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.650,
        "budget_raw": "Rp 1,65 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Summarecon Agung Tbk",
        "unor": "Commercial Lifestyle Center Gedebage",
        "balai": None,
        "fiscal_year": "2023",
        "progress": 100.0,
        "province": "Jawa Barat",
        "regency": "Kota Bandung",
        "latitude": -6.9550,
        "longitude": 107.6980,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jbr-020",
        "project_name": "Gedung Kantor Pusat BCA Foresta BSD City",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.900,
        "budget_raw": "Rp 900 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Central Asia Tbk",
        "unor": "Green Mark Platinum Corporate Center",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Banten",
        "regency": "Kabupaten Tangerang",
        "latitude": -6.3025,
        "longitude": 106.6420,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-022",
        "project_name": "Menara Bank Panin Senayan Sudirman",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.850,
        "budget_raw": "Rp 850 Miliar",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Bank Pan Indonesia Tbk",
        "unor": "Financial Center Tower",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Pusat",
        "latitude": -6.2230,
        "longitude": 106.8020,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-023",
        "project_name": "South Quarter Dome & Commercial Complex TB Simatupang",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 2.400,
        "budget_raw": "Rp 2,40 Triliun",
        "contractor": "PT Nusa Raya Cipta Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Intiland Development Tbk",
        "unor": "Grade-A Eco Business Park",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2930,
        "longitude": 106.7890,
        "source_url": "https://nusarayacipta.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jkt-024",
        "project_name": "Tokopedia Tower Ciputra World 2 Jakarta",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.950,
        "budget_raw": "Rp 1,95 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Ciputra Development Tbk",
        "unor": "Technology & Financial Hub (240 m)",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "DKI Jakarta",
        "regency": "Kota Jakarta Selatan",
        "latitude": -6.2220,
        "longitude": 106.8220,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-jtm-003",
        "project_name": "Pabrik Kertas PT Tjiwi Kimia Mojokerto Unit Baru",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 4.100,
        "budget_raw": "Rp 4,10 Triliun",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "Asia Pulp & Paper (APP Sinarmas)",
        "unor": "Paper Mill & Industrial Boiler Expansion",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Jawa Timur",
        "regency": "Kabupaten Mojokerto",
        "latitude": -7.4520,
        "longitude": 112.4850,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
    {
        "project_id": "swasta-mks-001",
        "project_name": "Trans Studio Mall & Hotel Complex Makassar",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 1.800,
        "budget_raw": "Rp 1,80 Triliun",
        "contractor": "PT Total Bangun Persada Tbk",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "CT Corp / Trans Retail",
        "unor": "Commercial Leisure & Business Hub",
        "balai": None,
        "fiscal_year": "2020",
        "progress": 100.0,
        "province": "Sulawesi Selatan",
        "regency": "Kota Makassar",
        "latitude": -5.1610,
        "longitude": 119.3950,
        "source_url": "https://totalbp.com",
        "source_name": "Laporan Kontrak Swasta / BUMN",
    },
    {
        "project_id": "swasta-mks-002",
        "project_name": "RS Siloam Hospital Makassar Tanjung Bunga",
        "category": "Commercial & Private",
        "status": "Operational",
        "budget_idr": 0.450,
        "budget_raw": "Rp 450 Miliar",
        "contractor": "PT Wijaya Karya (WIKA)",
        "funding_scheme": "Swasta Murni (Private)",
        "pjpk": "PT Siloam International Hospitals Tbk",
        "unor": "Tertiary Referral Hospital",
        "balai": None,
        "fiscal_year": "2021",
        "progress": 100.0,
        "province": "Sulawesi Selatan",
        "regency": "Kota Makassar",
        "latitude": -5.1550,
        "longitude": 119.4050,
        "source_url": "https://wika.co.id",
        "source_name": "Laporan Kontrak BUMN / Proyek Swasta",
    },
]


def main():
    conn = sqlite3.connect(str(DB_PATH))
    c = conn.cursor()

    upsert_sql = """
    INSERT INTO projects (
        project_id, project_name, category, status, budget_idr, budget_raw,
        contractor, funding_scheme, pjpk, unor, balai, fiscal_year, progress,
        bim_viewer_url, bim_uuid, province, regency, latitude, longitude,
        geocode_method, source_url, source_name, scraped_at
    ) VALUES (
        :project_id, :project_name, :category, :status, :budget_idr, :budget_raw,
        :contractor, :funding_scheme, :pjpk, :unor, :balai, :fiscal_year, :progress,
        :bim_viewer_url, :bim_uuid, :province, :regency, :latitude, :longitude,
        :geocode_method, :source_url, :source_name, :scraped_at
    )
    ON CONFLICT(project_id) DO UPDATE SET
        project_name=excluded.project_name,
        category=excluded.category,
        status=excluded.status,
        budget_idr=excluded.budget_idr,
        budget_raw=excluded.budget_raw,
        contractor=excluded.contractor,
        funding_scheme=excluded.funding_scheme,
        pjpk=excluded.pjpk,
        unor=excluded.unor,
        province=excluded.province,
        regency=excluded.regency,
        latitude=excluded.latitude,
        longitude=excluded.longitude,
        source_name=excluded.source_name,
        updated_at=datetime('now')
    """

    for p in COMMERCIAL_PROJECTS:
        record = {
            "project_id": p["project_id"],
            "project_name": p["project_name"],
            "category": p["category"],
            "status": p["status"],
            "budget_idr": p.get("budget_idr"),
            "budget_raw": p.get("budget_raw"),
            "contractor": p["contractor"],
            "funding_scheme": p["funding_scheme"],
            "pjpk": p["pjpk"],
            "unor": p.get("unor"),
            "balai": p.get("balai"),
            "fiscal_year": p.get("fiscal_year", "2024"),
            "progress": p.get("progress"),
            "bim_viewer_url": p.get("bim_viewer_url"),
            "bim_uuid": p.get("bim_uuid"),
            "province": p["province"],
            "regency": p["regency"],
            "latitude": p["latitude"],
            "longitude": p["longitude"],
            "geocode_method": "exact_kabupaten",
            "source_url": p.get("source_url", "https://ptpp.co.id"),
            "source_name": p.get("source_name", "Laporan Kontrak Swasta / BUMN"),
            "scraped_at": datetime.now().isoformat(),
        }
        c.execute(upsert_sql, record)

    conn.commit()
    conn.close()
    print(f"Upserted {len(COMMERCIAL_PROJECTS)} Commercial & Private projects into SQLite.")

    # Re-export GeoJSON
    feat_count, unres_count = export_geojson(GEOJSON_PATH)
    print(f"Exported {feat_count} features to GeoJSON (unresolved: {unres_count}).")


if __name__ == "__main__":
    main()
